server:
  port: 9060
  mode: 'release'
  limitNum: 20
  # 是否使用redis
  useRedis: false

redis:
  Addr: '127.0.0.1:6379'
  password: '123456'
  db: 0

mysql:
  user: root
  password: '123456'
  path: '127.0.0.1:3306'
  database: 'test'
  config: 'charset=utf8&parseTime=True&loc=Local'
  driver: 'mysql'
  maxIdleConns: 10
  maxOpenConns: 100
  log: false
  # url: 'root:123456@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local'

mongo:
  database: 'test'
  url: 'mongodb://127.0.0.1:27017'

log:
  accessLogName: 'logs/access.log'
  errorLogName: 'logs/error.log'
  
url:
  prefix: '/api/v1/gin-app-start'