server:
  port: ':9060'
  mode: 'release'
  readTimeout: 120000
	writeTimeout: 120000
	limitNum: 20

redis:
  host: '127.0.0.1'
  port: 6379
  password: ''
  db: 0
  useRedis: false

mysql:
  user: root
  password: '123456'
  host: '127.0.0.1'
  port: 3306
  database: 'test'
  config: 'charset=utf8&parseTime=True&loc=Local'
	driver: 'mysql'
	# url: 'root:123456@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local'
	maxIdleConns: 10
	maxOpenConns: 100
  log-mode: false

mongo:
  url: 'mongodb://127.0.0.1:27017'

log:
  accessLogName: 'logs/access.log'
  errorLogName: 'logs/error.log'